INSERT INTO stocks (symbol, name) VALUES ('RELIANCE', 'Reliance Industries Ltd');
INSERT INTO stocks (symbol, name) VALUES ('TCS', 'Tata Consultancy Services Ltd');
INSERT INTO stocks (symbol, name) VALUES ('INFY', 'Infosys Ltd');
INSERT INTO stocks (symbol, name) VALUES ('HDFCBANK', 'HDFC Bank Ltd');
INSERT INTO stocks (symbol, name) VALUES ('ICICIBANK', 'ICICI Bank Ltd');
INSERT INTO stocks (symbol, name) VALUES ('SBIN', 'State Bank of India');
INSERT INTO stocks (symbol, name) VALUES ('HINDUNILVR', 'Hindustan Unilever Ltd');
INSERT INTO stocks (symbol, name) VALUES ('ITC', 'ITC Ltd');
INSERT INTO stocks (symbol, name) VALUES ('KOTAKBANK', 'Kotak Mahindra Bank Ltd');
INSERT INTO stocks (symbol, name) VALUES ('BHARTIARTL', 'Bharti Airtel Ltd');
INSERT INTO stocks (symbol, name) VALUES ('LT', 'Larsen & Toubro Ltd');
INSERT INTO stocks (symbol, name) VALUES ('ASIANPAINT', 'Asian Paints Ltd');
INSERT INTO stocks (symbol, name) VALUES ('MARUTI', 'Maruti Suzuki India Ltd');
INSERT INTO stocks (symbol, name) VALUES ('AXISBANK', 'Axis Bank Ltd');
INSERT INTO stocks (symbol, name) VALUES ('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd');
INSERT INTO stocks (symbol, name) VALUES ('TITAN', 'Titan Company Ltd');
INSERT INTO stocks (symbol, name) VALUES ('TATASTEEL', 'Tata Steel Ltd');
INSERT INTO stocks (symbol, name) VALUES ('WIPRO', 'Wipro Ltd');
INSERT INTO stocks (symbol, name) VALUES ('POWERGRID', 'Power Grid Corporation of India Ltd');
INSERT INTO stocks (symbol, name) VALUES ('ULTRACEMCO', 'UltraTech Cement Ltd');
INSERT INTO stocks (symbol, name) VALUES ('HCLTECH', 'HCL Technologies Ltd');
INSERT INTO stocks (symbol, name) VALUES ('NTPC', 'NTPC Ltd');
INSERT INTO stocks (symbol, name) VALUES ('BAJFINANCE', 'Bajaj Finance Ltd');
INSERT INTO stocks (symbol, name) VALUES ('ADANIENT', 'Adani Enterprises Ltd');
INSERT INTO stocks (symbol, name) VALUES ('ADANIGREEN', 'Adani Green Energy Ltd');
